### ISSUE TITLE
Can we use only `${}` instead of `$xxx`?

### ISSUE THREAD

**Issue by g-kawin** [motdotla/dotenv-expand#42]
Some sensitive data like Database password might be possible to contain the special char like `$`. It transformed to white-space instead of the original characters. So, Is it possible to enforce and use only one replacement pattern like `${xx}`?

**Comment by mutantcornholio** [comment]
Why don't just wrap it in single quotes?

**Comment by mutantcornholio** [comment]
I've tested that out and it doesn't work :D 
Maybe that's what should be fixed

**Comment by LuXDAmore** [comment]
I have the same problem, my AUTH_KEY is like

> AUTH_KEY="Iluho$EkZ8-9U!*Fz4!7"

And is always resolving as:

> AUTH_KEY="Iluhoundefined-9U!*Fz4!7"

___

This is a problem because it's a common way to have dollars in config.
ex. [Wordpress ](https://wordpress.org/support/article/editing-wp-config-php/#security-keys) or [PHP](https://www.php.net/manual/en/function.password-verify.php).

**Comment by g-kawin** [comment]
Thanks, @LuXDAmore for your advice. It works well for me.
PS. If you really want only `$` or special characters. Just puts only one backslash in front of the symbol.

**Comment by LuXDAmore** [comment]
@g-kawin I'm using it in a [Nuxt](https://nuxtjs.org/) environment, as described [here](https://nuxtjs.org/guide/runtime-config/#-code-env-code-support), and putting only one `\` backslash, doesn't solve the problem..

But, I've fixed it trying with 2 `\\` 🤷‍♂️

**Comment by g-kawin** [comment]
> @g-kawin I'm using it in a [Nuxt](https://nuxtjs.org/) environment, as described [here](https://nuxtjs.org/guide/runtime-config/#-code-env-code-support), and putting only one `\` backslash, doesn't solve the problem..
> 
> But, I've fixed it trying with 2 `\\` 🤷‍♂️

BTW,  double backslash doesn't work on the Serverless framework with serverless-dotenv-plugin. Please be careful.

**Comment by gustavotoyota** [comment]
This feature would be very useful for me.

In CapRover the environment variables don't need a \ to mark dollar signs that aren't expansions, so whenever I have to move environment variables from CapRover to local I need to find all $ and add a \ before them, which is annoying and error-prone.

Also, this would allow variable expansion to be aligned with the usage of backticks in Javascript:
```
const MY_VAR = 123;

console.log(`hello$world`); // hello$world
console.log(`hello${MY_VAR}world`); // hello123world
console.log(`hello\${MY_VAR}world`); // hello${MY_VAR}world
```
While if I try the same in dotenv-expand:
```
MY_VAR=123

TEST1=hello$world # hello
TEST2=hello${MY_VAR}world # hello123world
TEST3=hello\${MY_VAR}world # hello${MY_VAR}world
```
